import {
 GET_ALBUM_COLLABORATORS_START,
 GET_ALBUM_COLLABORATORS_SUCCESS,
 GET_ALBUM_COLLABORATORS_FAILURE,

 PUT_ALBUM_COLLABORATORS_START, 
 PUT_ALBUM_COLLABORATORS_SUCCESS,
 PUT_ALBUM_COLLABORATORS_FAILURE,

 DELETE_ALBUM_COLLABORATOR_START,
 DELETE_ALBUM_COLLABORATOR_SUCCESS,
 DELETE_ALBUM_COLLABORATOR_FAILURE 
} from './types';