export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN';
export const NOT_YET_LOGGED_IN = 'NOT_YET_LOGGED_IN';



// album action types
export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAILURE = 'CREATE_ALBUM_FAILURE';

export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILURE = 'GET_ALBUMS_FAILURE';

export const EDIT_ALBUM_REQUEST = 'EDIT_ALBUM_REQUEST';
export const EDIT_ALBUM_SUCCESS = 'EDIT_ALBUM_SUCCESS';
export const EDIT_ALBUM_FAILURE = 'EDIT_ALBUM_FAILURE';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAILURE = 'DELETE_ALBUM_FAILURE';

// albumMetadata action types 
export const ADD_ALBUM_METADATA_REQUEST = 'ADD_ALBUM_METADATA_REQUEST';
export const ADD_ALBUM_METADATA_SUCCESS = 'ADD_ALBUM_METADATA_SUCCESS';
export const ADD_ALBUM_METADATA_FAILURE = 'ADD_ALBUM_METADATA_FAILURE';

export const GET_ALBUM_METADATA_REQUEST = 'GET_ALBUM_METADATA_REQUEST';
export const GET_ALBUM_METADATA_SUCCESS = 'GET_ALBUM_METADATA_SUCCESS';
export const GET_ALBUM_METADATA_FAILURE = 'GET_ALBUM_METADATA_FAILURE';

export const EDIT_ALBUM_METADATA_REQUEST = 'EDIT_ALBUM_METADATA_REQUEST';
export const EDIT_ALBUM_METADATA_SUCCESS = 'EDIT_ALBUM_METADATA_SUCCESS';
export const EDIT_ALBUM_METADATA_FAILURE = 'EDIT_ALBUM_METADATA_FAILURE';

export const DELETE_ALBUM_METADATA_REQUEST = 'DELETE_ALBUM_METADATA_REQUEST';
export const DELETE_ALBUM_METADATA_SUCCESS = 'DELETE_ALBUM_METADATA_SUCCESS';
export const DELETE_ALBUM_METADATA_FAILURE = 'DELETE_ALBUM_METADATA_FAILURE';

//Search Bar action types

export const SEARCH_START   = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS' ;
export const SEARCH_FAILURE = 'SEARCH_FAILURE';



//Collaborators Overview Action types

export const GET_ALBUM_COLLABORATORS_START = "GET_ALBUM_COLLABORATORS_START";
export const GET_ALBUM_COLLABORATORS_SUCCESS = "GET_ALBUM_COLLABORATORS_SUCCESS";
export const GET_ALBUM_COLLABORATORS_FAILURE = "GET_ALBUM_COLLABORATORS_FAILURE";

export const PUT_ALBUM_COLLABORATORS_START = "PUT_ALBUM_COLLABORATORS_START";
export const PUT_ALBUM_COLLABORATORS_SUCCESS = "PUT_ALBUM_COLLABORATORS_SUCCESS";
export const PUT_ALBUM_COLLABORATORS_FAILURE = "PUT_ALBUM_COLLABORATORS_FAILURE";

export const DELETE_ALBUM_COLLABORATOR_START = "DELETE_ALBUM_COLLABORATOR_START";
export const DELETE_ALBUM_COLLABORATOR_SUCCESS = "DELETE_ALBUM_COLLABORATOR_START";
export const DELETE_ALBUM_COLLABORATOR_FAILURE = "DELETE_ALBUM_COLLABORATOR_START";